### ISSUE TITLE
bot always offline

### ISSUE THREAD

**Issue by marielaulu** [matthew-robertson/vore-tracker#4]
the bot is always offline and never responds to commands or mentions of vore. i'm not sure if this is a coding error or user error

**Comment by matthew-robertson** [comment]
I took the bot offline about 9 months ago after some hosting issues that I didn't really want to fix, so not quite a code issue or a user issue. Since there seems to be some demand for it to come back, I'll get it running again and let you know once it's back up.

As an alternative, everyone is more than welcome to use the code I have here to run their own instance of the bot (you would have to set up a bot user on discord and host it yourself though)

**Comment by Valen8932** [comment]
Ah, I see. Thanks for letting us know! I had figured I may possibly have to look into hosting, though have never done so before. If I wanted to host my own instance, would there be anything I would need to add to the code to do so?

**Comment by matthew-robertson** [comment]
You'll need to add your bot's api key to the bottom of bot.py, where it says "----YOURKEYHERE----". As per usual, don't store said key in a publicly accessible place (The reason I initially took the bot down was I accidentally put the old key on this github, and decided to leave it down instead of setting up a better hosting situation).

If you don't particularly want to host your own, I imagine I can get a heroku instance running the bot (it should properly support as many servers as you toss it on, so it's not like every server needs its own) properly by end of day tomorrow, if not tonight, and either way I'm more than happy to continue to do development on the bot if there's interest in specific features/fixes. 

Best of luck!

**Comment by matthew-robertson** [comment]
It lives.

**Comment by sleeplessram** [comment]
the bot is offline again, is it down for updates?

**Comment by matthew-robertson** [comment]
Should be back up. I'll have to look into what happened there.

**Comment by sleeplessram** [comment]
shit haha, it detected vore once, set the text twice and then stopped sending text. could it be something on my end

**Comment by matthew-robertson** [comment]
Not your end. Looks like I accidentally set up multiple instances of the bot running. I'll restart it in a moment.

It's intentional that the bot only sends a message once every half hour to prevent spam. There are plans for a per-server customized cooldown, and given how many times I've been asked about this it might be time I implement it.

**Comment by sleeplessram** [comment]
thank you!!
